BEGIN TRANSACTION;
CREATE TABLE "user" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`login`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL,
	`firstname`	TEXT NOT NULL,
	`lastname`	TEXT NOT NULL,
	`session_id`	INTEGER
);
CREATE TABLE "session_entry" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`seconds`	INTEGER NOT NULL DEFAULT 0,
	`avg_speed`	REAL NOT NULL DEFAULT 0.0,
	`speed`	REAL NOT NULL DEFAULT 0.0,
	`session_id`	INTEGER NOT NULL,
	`distance`	INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE "session" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`distance`	INTEGER NOT NULL DEFAULT 0,
	`max_speed`	REAL NOT NULL DEFAULT 0.0,
	`avg_speed`	REAL DEFAULT 0.0,
	`start`	INTEGER NOT NULL DEFAULT current_timestamp,
	`end`	INTEGER NOT NULL DEFAULT current_timestamp,
	`user_id`	INTEGER NOT NULL,
	`device_id`	INTEGER NOT NULL,
	`active`	INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE "device" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`mac`	TEXT NOT NULL UNIQUE,
	`human`	TEXT NOT NULL UNIQUE,
	`active`	INTEGER NOT NULL DEFAULT 0
);
COMMIT;
